djangoProject/djangoBooks/urls.py
from django.urls import path 
from .views import *

app_name = 'djangoBooks'

urlpatterns = [
    path('', books_list.as_view(), name='list'),
    path('detail', books_detail.as_view(), name='detail'),
]

djangoProject/djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mainpage, name='main'),  #name 파라미터로 간편한 이름 설정 가능
    path('books/', include('djangoBooks.urls')),
]

djangoProject/djangoBooks/models.py
from django.db import models

class Book(models.Model):
    isbn13 = models.CharField(primary_key=True, max_length=13)
    vol = models.CharField(max_length=20, blank=True, null=True)
    title = models.CharField(max_length=1200, blank=True, null=True)
    author = models.CharField(max_length=1000, blank=True, null=True)
    publisher = models.CharField(max_length=1000, blank=True, null=True)
    pub_date = models.CharField(max_length=10, blank=True, null=True)
    img_url = models.CharField(max_length=1000, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    kdc_class_no = models.CharField(max_length=20, blank=True, null=True)

class Meta:
    db_table = u'books'

djangoProject/djangoBooks/views.py
from django.shortcuts import render
from django.views.generic import View
from .models import *
from django.core.paginator import Paginator

# Create your views here.

class books_list(View):
    context = {}
    template_name = 'books_list.html' #기본 템플릿 이름 설정

    #GET 통신
    def get(self,request):    
        books = Book.objects.all()
        page = int(request.GET.get('page', 1)) #페이지값을 전달받지 못하면 1로 설정
        # 해당 통신이 Ajax인지 확인 -> 페이지네이션 요청인지 확인하는 방법
        if request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest':
        	# Ajax라면 표현할 페이지 템플릿을 변경
            self.template_name = 'books_table.html'
        # 페이지네이터로 구분 -> 5개 아이템을 표시
        paginator = Paginator(books, 5)
        # 페이지 선택
        books_list = paginator.get_page(page)
        #도서 리스트를 저장
        self.context = {"books_list":books_list}
        return render(request, self.template_name, self.context) 
       
    #POST 통신
    def post(self,request):
        return render(request, self.template_name, self.context)
    
class books_detail(View):
    context = {}
    template_name = 'books_detail.html'

    def get(self, request):
        return render(request, self.template_name, self.context)
    def post(self, request):
        
        return render(request, self.template_name, self.context)

djangoProject/djangoProject/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import View

def mainpage(request):
    return render(request, 'mainpage.html')

djangoProject/djangoBooks/templates/books_detail.html
<html lang="ko">
    <head>
        <meta charset="UTF-8">
        <title>장고 북스</title>
    </head>
    <body>
        도서 상세 페이지
    </body>
</html> 

djangoProject/djangoBooks/templates/books_list.html
<html lang="ko">
    <head>
        <meta charset="UTF-8">
         <!-- Ajax 설정-->
        <script src="https://kit.fontawesome.com/f9a809ddea.js" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="http://code.jquery.com/jquery-latest.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
        <title>장고 북스</title>
    </head>
    <body>
        {% extends 'base.html' %}
        {% block content %}
        {% load static %}
            도서 목록 페이지    
            {% include 'books_table.html' %}
        {% endblock %}   
        {% if books_list %} <!-- 매핑된 도서 리스트가 있는지, 있다면 내용이 있는지 확인 -->
        <div class="row">
            <div class="book-items">
                {% for book in books_list %} <!-- 반복문을 통해 도서에 대한 내용 출력 -->
                 <div class="col-12 item">              
                    <img src="{{book.img_url}}">
                    <div class="metadata">
                        <div class="title">
                            {{book.title}} <!-- 각 반복문 대상의 요소 불러오기 -->
                        </div>
                        <table class="bibil">
                            <tr>
                                <th>저자</th>
                                <td>{{book.author}}</td>
                                <th>출판사</th>
                                <td>{{book.publisher}}</td>
                                <th>출판년도</th>
                                <td>{{book.pub_date}}</td>
                            </tr>
                            <tr>
                                <th>주제</th>
                                <td>{{book.kdc_class_no}}</td>
                                <th>ISBN</th>
                                <td>{{book.isbn13}}</td>
                                <th></th>
                                <td></td>
                            </tr>
                        </table>
                    </div>
                </div>
                {% endfor %} <!-- 중요한 점은 반복문의 끝에는 항상 이렇게 end를 넣어주어야 한다. -->
            </div>
        </div>             
        {% else %}
        <div class="row">
            <div class="col-12">
                <div class="no-result">
                    <p><b>{{search_input}}</b>도서가 없습니다</p>
                </div>
            </div>
        </div>
        {% endif %}
      </body>
</html> 

djangoProject/djangoBooks/templates/books_table.html
{% load static %}
<div id="table">
    <!-- 도서 목록 출력 부분 -->
  {% if books_list %} <!-- 매핑된 도서 리스트가 있는지, 있다면 내용이 있는지 확인 -->
  <div class="row">
      <div class="book-items">
            {% for book in books_list %} <!-- 반복문을 통해 도서에 대한 내용 출력 -->
            <div class="col-12 item">
                {% if book.img_url %}
                <img src="{{book.img_url}}">
                {% else %}
                <img src="{% static 'img/no_book_image.png' %}">
                {% endif %}
                <div class="metadata">
                    <div class="title">
                      {{book.title}} <!-- 각 반복문 대상의 요소 불러오기 -->
                    </div>
                    <table class="bibil">
                      <tr>
                          <th>저자</th>
                          <td>{{book.author}}</td>
                          <th>출판사</th>
                          <td>{{book.publisher}}</td>
                          <th>출판년도</th>
                          <td>{{book.pub_date}}</td>
                      </tr>
                      <tr>
                          <th>주제</th>
                          <td>{{book.kdc_class_no}}</td>
                          <th>ISBN</th>
                          <td>{{book.isbn13}}</td>
                          <th></th>
                          <td></td>
                      </tr>
                    </table>
                </div>
            </div>
            {% endfor %} <!-- 중요한 점은 반복문의 끝에는 항상 이렇게 end를 넣어주어야 한다. -->
        </div>
    </div>
    <!-- 페이지네이션 부분 -->
    <div class="row justify-content-center">
        <div class="col-8 pagination">
            <!-- 처음으로 버튼 -->
            {% if books_list.has_previous %}
            <a class="first_page"><i class="fa-solid fa-chevron-left"></i></a>
            {% endif %}
             <!-- 각 페이지 버튼 -->
            {% for page in books_list.paginator.page_range %}
                {% if page >= books_list.number|add:-5 and page <= books_list.number|add:5 %}
                    {% if page == books_list.number%}
                        <a class="now_page"><b>{{page}}</b></a>  <!-- 현재 페이지인 경우 Bold 사용 -->
                    {%else%}
                        <a class="now_page">{{page}}</a>
                    {% endif %}                        
                {% endif %}
            {%endfor %}            
            <!-- 마지막으로 버튼 -->   
            {% if books_list.has_next %}
            <a class="last_page" value={{books_list.paginator.num_pages}}><i class="fa-solid fa-chevron-right"></i></a>
      <!-- value값을 페이지네이션을 통해 페이지네이션 마지막 페이지값을 전달힌다. -->
            {% endif %}         
        </div>
    </div>   
    <!-- 도서 목록이 없는 경우 -->
    {% else %}
    <div class="row">
        <div class="col-12">
            <div class="no-result">
                <p><b>{{search_input}}</b>도서가 없습니다</p>
            </div>
        </div>
    </div>
    {% endif %}
    </div>
    <!-- Ajax 기능 구현 -->
    <script>
    // 각 페이지네이션 버튼 클릭에 따른 결과 전달
    $('.first_page').click(function () {
        num_pages = 1;
        page_click();
    })
    $('.now_page').click(function () {
        num_pages = parseInt($(this).text());
        page_click();
    })
    $('.last_page').click(function () {
        num_pages = parseInt($(this).attr("value"));
        page_click();
    })
        //페이지 클릭 시 작동방식
    function page_click() {
        $.ajax({
            type: "get", //GET 방식 사용
            url: "{% url 'djangoBooks:list' %}", //djangoBooks의 list url을 불러옴
            data: {
                'page': num_pages //GET 방식에 페이지 번호를 넣어서 전송
            },
            success: function (data) { //전송 성공시에 전송받는 데이터를 table class에 변경을 추가
                console.log(data)
                $('#table').html(data);
                window.scorllTo(0, 0);
            }
        })
    }
    </script>

djangoProject/djangoProject/templates/base.html
{% load static %}
<html lang="ko">
   <head>
      <meta charset="utf-8" />
      <!-- jquery와 ajax 설정 -->
      <script
         src="https://kit.fontawesome.com/f9a809ddea.js" crossorigin="anonymous"></script>
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="http://code.jquery.com/jquery-latest.js"></script>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
      <!-- 페이지 타이틀 설정 -->
      <title>장고북스</title>
      <!-- css 설정 -->
      <link rel="stylesheet" href="{% static 'css/style.css' %}" />
      {% block style %}
      <!-- 스타일 블록 -->
      {% endblock %}
   </head>
   <body>
      <!-- header 정의 -->
      <header>
         <!-- logo 정의 -->
         <a class="logo" href="{% url 'main' %}" >
               <!-- logo 이미지 및 이름 -->
               DjangoBooks <img class="logo" src="{% static 'img/django.png' %}"></a>         
         <!-- 네비게이션 바 정의 -->
         <nav>
            <span ><a class="menu" href="{% url 'djangoBooks:list' %}">도서목록</a></span>
         </nav>
      </header>
      {% block content %}
      <!-- 내용 -->
      {% endblock %}
      <footer>
         <!-- footer 정의 -->      
      </footer>
   </body>
</html>

djangoProject/djangoProject/templates/mainpage.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>이게 장고야 어</title>
</head>
<body>
    {% extends 'base.html' %}
    {% block content %}
    {% load static %}
      <h1>Django Books</h1>
      <p>이제 페이지를 하나씩 채워보도록 합시다.</p> 
    {% endblock %}
    <span class="menu"><a href="{% url 'djangoBooks:list' %}">도서목록</a></span>
</body>
</html>